use models::standings::FantasyContent;
use quick_xml::de::from_str;

pub mod models;

pub fn get_standings(xml: &str) -> FantasyContent {
    return from_str::<FantasyContent>(&xml).expect("TODO: error handle");
}

#[cfg(test)]
mod tests {
    use super::*;

fn get_standings_xml() -> &'static str {
    return r#"
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng" xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/league/223.l.431/standings" time="201.46489143372ms" copyright="Data provided by Yahoo! and STATS, LLC">
  <league>
    <league_key>223.l.431</league_key>
    <league_id>431</league_id>
    <name>Y! Friends and Family League</name>
    <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431</url>
    <draft_status>postdraft</draft_status>
    <num_teams>14</num_teams>
    <edit_key>17</edit_key>
    <weekly_deadline/>
    <league_update_timestamp>1262595518</league_update_timestamp>
    <scoring_type>head</scoring_type>
    <current_week>16</current_week>
    <start_week>1</start_week>
    <end_week>16</end_week>
    <is_finished>1</is_finished>
    <standings>
      <teams count="14">
        <team>
          <team_key>223.l.431.t.10</team_key>
          <team_id>10</team_id>
          <name>Gehlken</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/10</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/4b978f0ci2432zws140sp2/imXqmYo8cq3NxEFtQB4wgAs-/6/tn48.jpeg?ciA8DVOBMH.UXGXk</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>0</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>5</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>4LAITFUXFASDNAXFWUOHWNU3BY</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1682.33</total>
          </team_points>
          <team_standings>
            <rank>1</rank>
            <outcome_totals>
              <wins>9</wins>
              <losses>4</losses>
              <ties>0</ties>
              <percentage>.692</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>5</wins>
              <losses>1</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.5</team_key>
          <team_id>5</team_id>
          <name>RotoExperts</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/5</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/49be42a6i26e5zul3re3/d2x_9_UweKP95SJZ_Hwnk2Rl/2/tn48.jpg?ciA8DVOBIRa6b7wq</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>1</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>12</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>RW3ELDFMOFTES2EUAWQVCPPN7E</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1764.09</total>
          </team_points>
          <team_standings>
            <rank>2</rank>
            <outcome_totals>
              <wins>9</wins>
              <losses>4</losses>
              <ties>0</ties>
              <percentage>.692</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>4</wins>
              <losses>2</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.8</team_key>
          <team_id>8</team_id>
          <name>Y! - Pianowski</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/8</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://l.yimg.com/a/i/us/sp/fn/default/full/nfl/icon_10_48.gif</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>0</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>6</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>WMKEJTV3VUJA4VZWQ25O27W43M</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1569.48</total>
          </team_points>
          <team_standings>
            <rank>3</rank>
            <outcome_totals>
              <wins>8</wins>
              <losses>5</losses>
              <ties>0</ties>
              <percentage>.615</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>4</wins>
              <losses>2</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.12</team_key>
          <team_id>12</team_id>
          <name>Y! - Behrens</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/12</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://lookup.avatars.yahoo.com/images?yid=abehrens53&amp;size=medium&amp;type=jpg&amp;pty=3000</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>0</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>3</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>E2KS77CDQPACRTSBCYPOFFW6AI</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1652.27</total>
          </team_points>
          <team_standings>
            <rank>4</rank>
            <outcome_totals>
              <wins>8</wins>
              <losses>5</losses>
              <ties>0</ties>
              <percentage>.615</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>5</wins>
              <losses>1</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.4</team_key>
          <team_id>4</team_id>
          <name>Salfino-Comcast/NESN</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/4</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/4d8a517fi1b71zul1re3/ypdMGIA8cbVafvybuj2J.Jg-/2/tn48.jpg?ciA8DVOB5bipYD0R</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>0</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>9</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>PDLVXDDVXK2FRDI3FHRSS74F2U</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1621.98</total>
          </team_points>
          <team_standings>
            <rank>5</rank>
            <outcome_totals>
              <wins>7</wins>
              <losses>6</losses>
              <ties>0</ties>
              <percentage>.538</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>3</wins>
              <losses>3</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.11</team_key>
          <team_id>11</team_id>
          <name>FantasyGuru.com-Hans</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/11</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://lookup.avatars.yahoo.com/images?yid=fantasygurudotcom&amp;size=medium&amp;type=jpg&amp;pty=3000</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>1</faab_balance>
          <clinched_playoffs>1</clinched_playoffs>
          <managers>
            <manager>
              <manager_id>4</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>B7IJFDI5UUTN3AQ2F7ZEA4BDU4</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1469.00</total>
          </team_points>
          <team_standings>
            <rank>6</rank>
            <outcome_totals>
              <wins>7</wins>
              <losses>6</losses>
              <ties>0</ties>
              <percentage>.538</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>2</wins>
              <losses>4</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.1</team_key>
          <team_id>1</team_id>
          <name>PFW - Blunda</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/1</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://l.yimg.com/a/i/us/sp/fn/default/full/nfl/icon_01_48.gif</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>22</faab_balance>
          <managers>
            <manager>
              <manager_id>13</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>XNAXQZRDZPJ3RVFMY7ZTSWEFLU</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1461.71</total>
          </team_points>
          <team_standings>
            <rank>7</rank>
            <outcome_totals>
              <wins>7</wins>
              <losses>6</losses>
              <ties>0</ties>
              <percentage>.538</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>3</wins>
              <losses>3</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.2</team_key>
          <team_id>2</team_id>
          <name>Y! - Evans</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/2</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/4a68b2d6i2663zul3re3/HYebAP0zcqEPfMp3gOK8Mmbv/4/tn48.jpg?ciA8DVOBzMjxdtsK</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>35</faab_balance>
          <managers>
            <manager>
              <manager_id>8</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>RV2NLFT5LDNKUDOFSWSHIDINY4</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1512.53</total>
          </team_points>
          <team_standings>
            <rank>8</rank>
            <outcome_totals>
              <wins>6</wins>
              <losses>7</losses>
              <ties>0</ties>
              <percentage>.462</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>2</wins>
              <losses>4</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.13</team_key>
          <team_id>13</team_id>
          <name>Erickson - RotoWire</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/13</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://lookup.avatars.yahoo.com/images?yid=jeff_rotonews&amp;size=medium&amp;type=jpg&amp;pty=3000</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>17</faab_balance>
          <managers>
            <manager>
              <manager_id>11</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>SB4Y5HVVUKMCTKZFQCXHIZ222E</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1484.56</total>
          </team_points>
          <team_standings>
            <rank>9</rank>
            <outcome_totals>
              <wins>6</wins>
              <losses>7</losses>
              <ties>0</ties>
              <percentage>.462</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>3</wins>
              <losses>3</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.9</team_key>
          <team_id>9</team_id>
          <name>Y! - Funston</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/9</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://lookup.avatars.yahoo.com/images?yid=brandoanf1&amp;size=medium&amp;type=jpg&amp;pty=3000</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>10</faab_balance>
          <managers>
            <manager>
              <manager_id>1</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>3H7IQ3F2742K2ODHSJK5YXL23E</guid>
              <is_commissioner>1</is_commissioner>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1430.24</total>
          </team_points>
          <team_standings>
            <rank>10</rank>
            <outcome_totals>
              <wins>6</wins>
              <losses>7</losses>
              <ties>0</ties>
              <percentage>.462</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>2</wins>
              <losses>4</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.7</team_key>
          <team_id>7</team_id>
          <name>RotoWire_Liss</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/7</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://l.yimg.com/a/i/us/sp/fn/default/full/nfl/icon_10_48.gif</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>68</faab_balance>
          <managers>
            <manager>
              <manager_id>7</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>4BDB5LIG3IFVROH7SRBX44LBZM</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1424.56</total>
          </team_points>
          <team_standings>
            <rank>11</rank>
            <outcome_totals>
              <wins>6</wins>
              <losses>7</losses>
              <ties>0</ties>
              <percentage>.462</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>3</wins>
              <losses>3</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.3</team_key>
          <team_id>3</team_id>
          <name>RotoWire - Del Don</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/3</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://l.yimg.com/a/i/us/sp/fn/default/full/nfl/icon_05_48.gif</url>
            </team_logo>
          </team_logos>
          <division_id>2</division_id>
          <faab_balance>0</faab_balance>
          <managers>
            <manager>
              <manager_id>10</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>4A5KVYHC7ZSEGOBFHFSO5Q64VA</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1366.89</total>
          </team_points>
          <team_standings>
            <rank>12</rank>
            <outcome_totals>
              <wins>6</wins>
              <losses>7</losses>
              <ties>0</ties>
              <percentage>.462</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>3</wins>
              <losses>3</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.6</team_key>
          <team_id>6</team_id>
          <name>Y! - Romig</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/6</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/49b954dci229az/IJtbcRQjdKtd_DMoStSK/103/tn48.jpg?ciA8DVOB2WQ2Fk4F</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>0</faab_balance>
          <managers>
            <manager>
              <manager_id>2</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>FS5M5LOFJRKVJNRIWG36ZUF7IQ</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1370.16</total>
          </team_points>
          <team_standings>
            <rank>13</rank>
            <outcome_totals>
              <wins>5</wins>
              <losses>8</losses>
              <ties>0</ties>
              <percentage>.385</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>2</wins>
              <losses>4</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
        <team>
          <team_key>223.l.431.t.14</team_key>
          <team_id>14</team_id>
          <name>Y! - Chase</name>
          <url>https://football.fantasysports.yahoo.com/archive/pnfl/2009/431/14</url>
          <team_logos>
            <team_logo>
              <size>medium</size>
              <url>https://a323.yahoofs.com/coreid/4a7a23a5icfazul2re3/2fIcrk8yc7QS3j_ei4PULEbpFA--/1/tn48.jpg?ciA8DVOBcEQk3vWZ</url>
            </team_logo>
          </team_logos>
          <division_id>1</division_id>
          <faab_balance>92</faab_balance>
          <managers>
            <manager>
              <manager_id>14</manager_id>
              <nickname>-- hidden --</nickname>
              <guid>7CSOKBMM74MGFMSWHWJMM4FBQ4</guid>
            </manager>
          </managers>
          <team_points>
            <coverage_type>season</coverage_type>
            <season>2009</season>
            <total>1237.47</total>
          </team_points>
          <team_standings>
            <rank>14</rank>
            <outcome_totals>
              <wins>1</wins>
              <losses>12</losses>
              <ties>0</ties>
              <percentage>.077</percentage>
            </outcome_totals>
            <divisional_outcome_totals>
              <wins>1</wins>
              <losses>5</losses>
              <ties>0</ties>
            </divisional_outcome_totals>
          </team_standings>
        </team>
      </teams>
    </standings>
  </league>
</fantasy_content>
"#;
}


    #[test]
    fn it_works() {
        let xml = get_standings_xml();
        let result = get_standings(xml);
        // println!("{:#?}", result);
        // assert_eq!(result, 4);
    }
}
