name: Conditional Set

on:
  workflow_call:
    inputs:
      env: # ["stg", "prod"]
        type: string
        required: true

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - id: set-destination-prefix
        name: Set Destination Prefix
        if: always()
        run: |
          echo "value=fromJSON('["stag", "prod"]')[${{ inputs.env }} == "prod"]" >> $GITHUB_OUTPUT
      - name: Echo Value
        run: |
          echo value: ${{ steps.set-destination-prefix.outputs.value }}
      - name: Echo Eko
        run: |
          echo EKO
