name: Echo secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Not Implemented Yet
        run: |
          printenv YAHOO_OAUTH_CLIENT_ID
          echo '${{ secrets.YAHOO_OAUTH_TOKEN_URL}}'
          echo ${{ secrets.CORS_REVERSE_PROXY_ENDPOINT}}
