name: OutputStateTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set
        id: set
        run: |
          my_var="my_value_2"
          echo "my_var=$(my_value)" >> $GITHUB_OUTPUT
      - name: Read
        run: |
          echo ${{ steps.set.outputs.my_var }}
