name: Use Local WF

on:
  workflow_dispatch:

jobs:
  build:
    # uses: "./.github/workflows/echo-branch.yml"
    # uses: "n-ae/nba-fantasy/.github/workflows/echo-branch.yml@test"
    uses: "./.github/workflows/conditional-set.yml"
    with:
      # env: "stg"
      env: "prod"
