name: Use Local WF

on:
  workflow_dispatch:

jobs:
  build:
    # uses: "./.github/workflows/echo-branch.yml"
    # uses: "bali-ibrahim/nba-fantasy/.github/workflows/echo-branch.yml@test"
    uses: "./.github/workflows/conditional-set.yml"
    with:
      env: "stg"
